OdeFood/Pages/Error.cshtml.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace OdeFood.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

OdeFood/Pages/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace OdeFood.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;

        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {

        }
    }
}

OdeFood/Pages/Privacy.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace OdeFood.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

OdeFood/Pages/Restruants/ClintsideRestaurants.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace OdeFood
{
    public class ClintsideRestaurantsModel : PageModel
    {
        public void OnGet()
        {

        }
    }
}

OdeFood/Pages/Restruants/Delete.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using OdeToFood.Core;
using OdeToFood.Data;

namespace OdeFood
{
    public class DeleteModel : PageModel
    {
        private IRestaurantData _restaurantData;
        public Restaurant Restaurant { get; set; }
        public DeleteModel(IRestaurantData restaurantData)
        {
            _restaurantData = restaurantData;
        }
        public IActionResult OnGet(int restaurantId)
        {
            Restaurant = _restaurantData.GetRestaurantById(restaurantId);
            if(Restaurant==null)
            {
                return RedirectToPage("./NotFound");
            }
            return Page();
        }
        public IActionResult OnPost(int restaurantId)
        {
            var restturant = _restaurantData.Delete(restaurantId);
            _restaurantData.Commit();
            if(restturant == null)
            {
                return RedirectToPage("./NotFound");
            }
            TempData["Message"] = $"{restturant.Name} is deleted";
            return RedirectToPage("./List");
        }
    }
}

OdeFood/Pages/Restruants/Details.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using OdeToFood.Core;
using OdeToFood.Data;

namespace OdeFood
{
    public class DetailsModel : PageModel
    {
        private IRestaurantData _restaurantData;

        public DetailsModel(IRestaurantData restaurantData)
        {
            _restaurantData = restaurantData;
        }
        [TempData]
        public string Message { get; set; }
        public Restaurant Restaurant { get; set; }
        public IActionResult OnGet(int restaurantId)
        {
            Restaurant = _restaurantData.GetRestaurantById(restaurantId);
            if(Restaurant==null)
            {
                return RedirectToPage("./NotFound");
            }
            return Page();
        }
    }
}

OdeFood/Pages/Restruants/Edit.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using OdeToFood.Core;
using OdeToFood.Data;
using System.Collections.Generic;

namespace OdeFood
{
    public class EditModel : PageModel
    {
        private IRestaurantData _restaurantData;
        private IHtmlHelper _htmlHelper;

        public EditModel(IRestaurantData restaurantData,IHtmlHelper htmlHelper)
        {
            _restaurantData = restaurantData;
            _htmlHelper = htmlHelper;
        }
        [BindProperty]
        public Restaurant Restaurant { get; set; }
        public IEnumerable<SelectListItem> Cuisines { get; set; }
        public IActionResult OnGet(int? restaurantId)
        {
            Cuisines = _htmlHelper.GetEnumSelectList<CuisineType>();
            if(restaurantId.HasValue)
            {
                Restaurant = _restaurantData.GetRestaurantById(restaurantId.Value);
            }
            else
            {
                Restaurant = new Restaurant();
            }
            if (Restaurant==null)
            {
                return RedirectToPage("./NotFound");
            }
            return Page();
        }
        public IActionResult OnPost()
        {
            if(!ModelState.IsValid)
            {
                Cuisines = _htmlHelper.GetEnumSelectList<CuisineType>();
                return Page();
            }
            if(Restaurant.Id>0)
            {
                _restaurantData.Update(Restaurant);
               
            }
            else
            {
               _restaurantData.Add(Restaurant);
            }
            TempData["Message"] = "Resturant is Saved";
            _restaurantData.Commit();
            return RedirectToPage("./Details", new { restaurantId = Restaurant.Id });

        }
    }
}

OdeFood/Pages/Restruants/List.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Configuration;
using OdeToFood.Core;
using OdeToFood.Data;
using System.Collections.Generic;

namespace OdeFood
{
    public class ListModel : PageModel
    {
        private IConfiguration _confg;
        private IRestaurantData _restaurantData;
        public IEnumerable<Restaurant> restaurant;
        public ListModel(IConfiguration confg, IRestaurantData restaurantData)
        {
            _confg = confg;
            _restaurantData = restaurantData;
        }
        public string Message { get; set; }

        [BindProperty(SupportsGet =true)]
        public string SearchTerm { get; set; }
        public void OnGet()
        {
            Message = _confg["Message"];
            restaurant = _restaurantData.GetRetaurantByName(SearchTerm);
        }
    }
}

OdeFood/ViewComponents/RestaurantCountViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using OdeToFood.Data;

namespace OdeFood.ViewComponents
{
    public class RestaurantCountViewComponent:ViewComponent
    {
        private IRestaurantData _restaurantData;

        public RestaurantCountViewComponent(IRestaurantData restaurantData)
        {
            _restaurantData = restaurantData;
        }
        public IViewComponentResult Invoke()
        {
            var count = _restaurantData.GetCountOfRestaurant();
            return View(count);
        }
    }
}

OdeFood/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

OdeFood/Pages/Restruants/ClintsideRestaurants.cshtml
@page
@model OdeFood.ClintsideRestaurantsModel
@{
    ViewData["Title"] = "ClintsideRestaurants";
}

<h1>ClintsideRestaurants</h1>

@section  Scripts{
    <script>
        $(function () {
            $.ajax("/api/restaurants/",
                { method: "get" }).then(function (response) {
                    console.dir(response);
                });
        });
    </script>

}

OdeFood/Pages/Restruants/Delete.cshtml
@page "{restaurantId}"
@model OdeFood.DeleteModel
@{
   
}


    <title>Delete</title>

    <div class="alert alert-danger">
        Are you sure you want to delete @Model.Restaurant.Name?
    </div>
    <form method="post">
        <button type="submit" class="btn btn-danger">
            Yes
        </button>
        <a asp-page="List" class="btn btn-secondary">Cancel</a>
    </form>

OdeFood/Pages/Restruants/Details.cshtml
@page "{restaurantId:int}"
@model OdeFood.DetailsModel
@{
    ViewData["Title"] = "Details";
}

<h2>@Model.Restaurant.Name</h2>
@if(Model.Message!=null)
{
    <div class="alert alert-info" >
        @Model.Message
    </div>
}
<div>
    Id: @Model.Restaurant.Id
</div>
<div>
    Location: @Model.Restaurant.Location
</div>
<div>
    Cuisine: @Model.Restaurant.Cuisine
</div>

<a asp-page="./List" class="btn btn-light">All Restaurants</a>

OdeFood/Pages/Restruants/Edit.cshtml
@page "{restaurantId:int?}"
@model OdeFood.EditModel
@{
    ViewData["Title"] = "Edit";
}
@if (Model.Restaurant.Id == 0)
{
    <h1>Add New Restaurant</h1>
}
else
{
    <h1>Editing @Model.Restaurant.Name</h1>
}


<form method="post">
    <input type="hidden" asp-for="Restaurant.Id" />
    <div class="form-group">
        <label asp-for="Restaurant.Name"></label>
        <input asp-for="Restaurant.Name" class="form-control" />
        <span class="text-danger" asp-validation-for="Restaurant.Name"></span>
    </div>
    <div class="form-group">
        <label asp-for="Restaurant.Location"></label>
        <input asp-for="Restaurant.Location" class="form-control" />
        <span class="text-danger" asp-validation-for="Restaurant.Location"></span>
    </div>
    <div class="form-group">
        <label asp-for="Restaurant.Cuisine"></label>
        <select class="form-control" asp-for="Restaurant.Cuisine" asp-items="Model.Cuisines">
        </select>
        <span class="text-danger" asp-validation-for="Restaurant.Cuisine"></span>
    </div>
    <button type="submit" class="btn btn-primary">Save</button>
</form>

@*@section Scripts{
        <partial name="_ValidationScriptsPartial" />

    }*@

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

OdeFood/Pages/Restruants/List.cshtml
@page
@model OdeFood.ListModel
@{
    ViewData["Title"] = "List";
}

<h1>Restaurants</h1>
<form method="get">
    <div class="form-group">
        <div class="input-group">
            <input type="search" class="form-control" placeholder="Search" asp-for="SearchTerm" />
            <div class="input-group-append">
                <button class="btn btn-light">
                    <i class="fa fa-search fa-fw"></i>
                </button>
            </div>
        </div>
    </div>
</form>
<div class="form-group">
    <div class="input-group">
        <a asp-page="./Edit" class="btn btn-primary">New Restaurant</a>
       
    </div>
</div>

<div class=" card-deck">
    @foreach (var rest in Model.restaurant)
    {
        <partial name="_Summary" model="rest" />
    }
    </div>

OdeFood/Pages/Restruants/NotFound.cshtml
@page
@{
    ViewData["Title"] = "NotFound";
}

<h2>Your restaurant was not found</h2>
<a asp-page="./List" class="btn btn-primary">See All Restaurants</a>

OdeFood/Pages/Restruants/_Summary.cshtml
@using OdeToFood.Core
@model Restaurant



    

        <div class="card" >
            <img class="card-img-top" src="..." alt="Card image cap">
            <div class="card-body">
                <h5 class="card-title">@Model.Name</h5>
                <span class="card-text">Location Is @Model.Location</span>
                <pre></pre>
                <span class="card-text">Cuisine Is @Model.Cuisine</span>
            </div>

            <div class="card-footer">
                <a class="btn btn-md" asp-page="./Details"
                   asp-route-restaurantId="@Model.Id">
                    <i class="fa fa-folder-open"></i>
                </a>

                <a class="btn btn-md" asp-page="./Edit"
                   asp-route-restaurantId="@Model.Id">
                    <i class="fa fa-edit"></i>
                </a>

                <a class="btn btn-md" asp-page="./Delete"
                   asp-route-restaurantId="@Model.Id">
                    <i class="fa fa-trash"></i>
                </a>
            </div>
        </div>

    

OdeFood/Pages/Shared/Components/RestaurantCount/Default.cshtml
@model int

<div class="font-weight-light">
    There are @Model restaurants here.<a asp-page="/Restruants/List">See Them All</a>
</div>

OdeFood/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - OdeFood</title>

    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css"
          integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous">
    <link rel="stylesheet" href="~/css/site.css" />

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">OdeFood</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Restruants/List">Restaurants</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <vc:restaurant-count></vc:restaurant-count>
        <div class="container">
            &copy; 2021 - OdeFood - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>
    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.min.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    

    @RenderSection("Scripts", required: false)
</body>
</html>